DROP DATABASE IF EXIST BDPrestamo;
CREATE DATABASE BDPrestamo;

USE BDPrestamo;

CREATE TABLE CLIENTE
(COD_CLI INT AUTO_INCREMENT PRIMARY KEY,
NOM_CLI VARCHAR(50),
APE_CLI VARCHAR (50),
DNI_CLI CHAR(8)
);

INSERT INTO CLIENTE VALUES(NULL,'JHON','SIESQUEN','12345678');
INSERT INTO CLIENTE VALUES(NULL,'FABIAN','UZURIAGA','12345679');
INSERT INTO CLIENTE VALUES(NULL,'FRANK','ULLILEN','12345670');
INSERT INTO CLIENTE VALUES(NULL,'ARNOLD','RODRGIGUEZ','12345671');

SELECT * FROM CLIENTE;
 

 DELIMITER $$
DROP PROCEDURE IF EXISTS SP_BUSDEL_CLIENTE;
CREATE PROCEDURE SP_BUSDEL_CLIENTE
( BUS VARCHAR(20),TIPO VARCHAR(3))
BEGIN
 IF  TIPO='B' THEN 
        SELECT*FROM CLIENTE  WHERE  COD_CLI=BUS  OR NOM_CLI LIKE  CONCAT('%',BUS,'%');
 ELSEIF TIPO='D' THEN 
        DELETE FROM CLIENTE  WHERE  COD_CLI=BUS;
    END IF ;
 END $$
DELIMITER $$